### ISSUE TITLE
Make `either` option the default

### ISSUE THREAD

**Issue by radiovisual** [validate-io/color-hexadecimal#1]
This is more of a question really:

Can you explain why the value of `'FFF'` will return `false` without  the `shorthand` option?

In my mind, the value of 'fff' is a valid Hex color. Or is my line of thinking only true because HTML (CSS) colors support the shorthand notation?

```js
isHexColor('FFF');
// returns false

isHexColor('FFF', 'shorthand');
// returns true
```

I am thinking that because this package is installed on npm, most of your users are using this package in the context of web development in JavaScript, with HTML/CSS colors in mind. With that said, I think that this should return `true`:

```js
isHexColor('FFF');
```
Since this module differentiates shorthand values with full values while HTML/CSS/JS does not, it seems to me that the `'either` option should be the default, where we only turn on the 'shorthand' or 'full' modes when we need that level of control..meaning both of these would return true:

 ```js
isHexColor('FFF');
// returns true

isHexColor('FFF', 'shorthand');
// returns true
```

Thinking further, it would also be awesome if we could chain our validations to make the validation steps super readable:

```js
isHexColor('FFF').and.is.shorthand;
// true

isHexColor('FFF').and.is.full;
// false

isHexColor('FFF').and.not.shorthand;
// false

isHexColor('FFF').and.not.full;
// true

isHexColor('FFF');
// true
```

But that is getting way ahead of myself. 😄

**Comment by kgryte** [comment]
@radiovisual Thanks for reaching out.

Re: chaining. I am not interested in supporting this style of API. First and foremost, this style of API diverges from the interface design of other validation functions in this organization.

Re: defaults. The 3-digit abbreviated form is, to my knowledge, only described in the CSS specification, not the HTML specification. Further, the 3-digit abbreviation is exactly that: an abbreviation. The most general form of a hexidecimal color is a six-digit sequence. 3-digit forms are a special case. Along a similar vein, the default behavior of this function is to treat shorthand forms as a special case.

My view is that special behavior/considerations should be opt-in, not opt-out. At the moment, I do not see a compelling enough reason to overrule this viewpoint.

Feel free to fork and create a version more tailored to your tastes and needs.

**Comment by radiovisual** [comment]
Thanks for the input. No worries. 

> The 3-digit abbreviated form is, to my knowledge, only described in the CSS specification, not the HTML specification.

Yeah, you are right, in the [HTML Color Specification](https://html.spec.whatwg.org/#colours), hex colors must be 7-characters long. Only the CSS spec supports the shorthand.

👍
